### ISSUE TITLE
jason identifiers

### ISSUE THREAD

**Issue by jomifred** [wfdd/language-agentspeak#1]
Hello, I am delighted to find this project! Thanks you.

I've just notice that underline is not considered as a valid character for identifiers, as in .my_name or VL_T, ....

thanks,

Jomi

**Comment by wfdd** [comment]
Thanks @jomifred.  I whipped this up overnight for a class a friend was teaching, so there's quite a lot to be desired!

**Comment by jomifred** [comment]
great! thanks very much.
